export interface Task {
  id: string;
  title: string;
  description?: string;
  status: string; // e.g., "To Do", "In Progress", "Completed"
  createdAt?: string; // Assuming backend provides these
  updatedAt?: string;
}

// Interface for creating a task, ID is usually generated by the backend
export interface CreateTaskPayload {
  title: string;
  description?: string;
  status?: string; // Default status can be handled by backend or frontend
}

// Interface for updating a task
export interface UpdateTaskPayload {
  title?: string;
  description?: string;
  status?: string;
}
